services:
  dev-linux:
    build:
      dockerfile: "Dockerfile.linux"
    command:
      - nvim
      - --headless
      - --listen
      - 0.0.0.0:7892
    working_dir: /workspace/net
    init: true
    restart: "always"
    ulimits:
      core: -1
    ports:
      - "7892:7892"
    volumes:
      - "$HOME/dotfiles/config/nvim/:/root/.config/nvim/"
      - "$HOME/dotfiles/config/git/:/root/.config/git/"
      - "../:/workspace/net"
      - nvim-plugins:/root/.local/share/nvim/
      - build-cache:/workspace/net/build/
      - user-cache:/root/.cache

volumes:
  nvim-plugins: {}
  build-cache: {}
  user-cache: {}
