name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
        cc: [gcc-11, clang-14]
        cxx: [g++-11, clang++-14]
        exclude:
        - cc: gcc-11
          cxx: clang++-14
        - cc: clang-14
          cxx: g++-11

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Select Linux Compilers
      if: runner.os == 'Linux'
      run: |
        echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

    - name: Select MacOS Compilers (Clang)
      if: runner.os == 'MacOS' && matrix.cc == 'clang-14'
      run: |
        echo "CC=$(brew --prefix llvm@14)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm@14)/bin/clang++" >> $GITHUB_ENV

    - name: Select MacOS Compilers (GCC)
      if: runner.os == 'MacOS' && matrix.cc == 'gcc-11'
      run: |
        echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ env.CC }} -DCMAKE_CXX_COMPILER=${{ env.CXX }} -DBUILD_TESTING=TRUE -DBUILD_EXAMPLE=TRUE -DCMAKE_MAKE_PROGRAM=make -B build/

    - name: Build
      run: cmake --build build/

    - name: Test
      run: ctest --test-dir build/
