name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{github.workspace}}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build/

    - name: Build
      run: cmake --build build/ --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} build/
